let data = ./data.dhall

in  ''
# ----- DO NOT EDIT: This file is autogenerated ----- #

# Options should imitate Ormolu's style
${(./Prelude.dhall).Text.concatMapSep
    "\n"
    data.Option
    ( \(option : data.Option) ->
        "${option.name}: ${data.showValuePretty option.ormolu}"
    )
    data.options}
fixities: []
''
