let data = ./data.dhall

let Prelude = ./Prelude.dhall

in ''
# ----- DO NOT EDIT: This file is autogenerated ----- #

# Options should imitate Ormolu's style
${Prelude.Text.concatMapSep
    "\n"
    data.Option
    ( \(option : data.Option) ->
        "${option.name}: ${data.showValuePretty option.ormolu}"
    )
    data.options}
fixities: []
''
